### ISSUE TITLE
[Feature]: Show user information for each "chatter"

### ISSUE THREAD

**Issue by morgnism** [thisdot/lets-chat-with#11]
### Is your feature request related to a problem? Please describe.

The info blocks for users are empty in the "Chatters" section.

![image](https://user-images.githubusercontent.com/9042219/218578809-24ce9254-a632-436c-8e6b-32a3aa5890cb.png)

### Describe the solution you'd like

Show some user information for each "chatter".

### Reproduction

_Note: you will need two authenticated instances of the app running to reproduce this scenario_

1. Authenticate into 2 accounts (one standard browser window and another incognito window)
2. Enter the same conference for both users
3. Connect the users by selecting the mutual role and interests
4. Navigate to "Chatters"
5. Click the blue "info" icon button
6. View the chatter's information

### Additional context

Suggested query to fix this:

![image](https://user-images.githubusercontent.com/9042219/218578853-d994dc95-02bd-4eec-afcf-43a011a07bb9.png)

**Comment by lindakatcodes** [comment]
This issue was resolved with PR #39
