### ISSUE TITLE
[Bug]: Unable to flag a chat connection

### ISSUE THREAD

**Issue by morgnism** [thisdot/lets-chat-with#12]
### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Actual Behavior

Unable to flag a chat connection. The button click is inactive.

![image](https://user-images.githubusercontent.com/9042219/218580002-161a07b6-9460-4975-86e6-29b8acffae8f.png)

### Expected Behavior

Clicking the report icon button should open the report flow.

### Reproduction

1. Sign in to the app
2. Select a conference
3. Select "Messages"
4. Select an ongoing message
5. Click the flag icon in the top right of the chat

### Additional Information

There is absolutely no functionality on this icon.

**Comment by Atrophius** [comment]
This flow seems reasonable, proceed.
