### ISSUE TITLE
[Bug]: Logging out and back in again shows the min-onboarding process again

### ISSUE THREAD

**Issue by morgnism** [thisdot/lets-chat-with#20]
### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Actual Behavior

When I log in again after logging out select a conference, I have to go through the min-onboarding process again.

### Expected Behavior

Reauthenticating after previously logging out and selecting a conference shouldn't show the min-onboarding flow again for each conference.

### Reproduction

1. Log out
2. Log back in

**Comment by Atrophius** [comment]
Go ahead with this proposal.

**Comment by morgnism** [comment]
The above proposal isn't quite correct to solving this problem. There needs to be some caching mechanism in place that determines whether or not the user has seen the min-onboarding post selecting a conference.

The option to see the instructions again can be in the support section.

**Comment by morgnism** [comment]
Closed because this flow persists when authenticating in an incognito browser.
